version: "3.3"
services:
  prometheus:
    image: prom/prometheus
    container_name: 'prometheus'
    user: "1001:1001"
    volumes:
      - ./prometheus/:/etc/prometheus/
      - ./prometheus/prometheus_data:/prometheus
    ports:
      - 9090:9090
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana:5.4.3
    container_name: 'grafana'
    volumes:
    - ./grafana/provisioning:/etc/grafana/provisioning
    - ./grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - 3000:3000

  register:
    build:
      dockerfile: ./kotlin-exposed-koin-javalin/app.dockerfile
      context: .
    image: register/javalin
    ports:
      - 7000:7000
    container_name: 'register-javalin'
    depends_on:
      - "postgresdb"

  postgresdb:
    image: postgres
    container_name: 'register-postgres'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres